### ISSUE TITLE
More guild checks

### ISSUE THREAD

**Issue by Dorukyum** [Dorukyum/Pycord-Manager#18]
- [ ] Server logs - new database field?
- [x] Suggestions
- [x] Automod
- [x] Mod logs
- [x] ~~AFK command~~

These might require new database models or fields.

**Comment by Batucho** [comment]
I could help you with this if you like.

**Comment by ephemeral8997** [comment]
#24 fixes this issue.

**Comment by Dorukyum** [comment]
> #24 fixes this issue.

This is a general issue and the mentioned pr doesn't close this, fyi.

**Comment by ephemeral8997** [comment]
> > #24 fixes this issue.
> 
> This is a general issue and the mentioned pr doesn't close this, fyi.

lol, I didn't realize this
