### ISSUE TITLE
[FEATURE REQUEST] Add `raid` command.

### ISSUE THREAD

**Issue by BruceCodesGithub** [Dorukyum/Pycord-Manager#19]
1. Asks the mod twice to confirm if there really is a raid, and that they are not joking about it
2. Asks the mod if general needs to be locked. If they say yes, lock it, if they do not respond or say no, don't.
3. Create a new channel and send an embed with info of all new members. The embed strip should be red if they are sus (new account, default PFP), black if they don't know). Info about when the account was made, their avatar, etc. should be in the embed. 
4. Each message should have 2 buttons - Timeout for 5m in case the mod isn't sure if the account is a fake one, Kick for the same reason, Ban if the mod is sure the account is an alt.
5. A way to stop the raid prevention.

### Restrictions
Moderator-only

**Comment by Dorukyum** [comment]
Update: a channel lock command has been added with https://github.com/Dorukyum/Pycord-Manager/commit/4b91c0df0295a87c9f799b103d4a9125dbc9509e.

**Comment by ephemeral8997** [comment]
Actually, this is not a required feature, since pycord manager is not the only moderation bot, but it's a good feature.

**Comment by BruceCodesGithub** [comment]
> Actually, this is not a required feature, since pycord manager is not the only moderation bot, but it's a good feature.

Pycord manager will soon be the only moderation bot. We are working on making it the main Moderation bot for Pycord.

**Comment by Dorukyum** [comment]
This system seems like overkill to me. A mod can just lock #general and the bot will timeout new members if they are young accounts and automod is on. The mods can then use the ban command for massban or ban the raiders one by one.
